### ISSUE TITLE
SRSF8 Not found in GSE92742

### ISSUE THREAD

**Issue by quietDragon1995** [MaayanLab/sigcom-lincs#23]
In GSE92742, GSE92742_Broad_LINCS_gene_info_delta_landmark.txt.gz has the gene SRSF8. However, 
SRSF8 doesn't show in the GSE92742_Broad_LINCS_gene_info.txt.gz. Could someone tell me why the SRSF8 is lost in GSE92742_Broad_LINCS_gene_info.txt.gz?

**Comment by sxie04** [comment]
Hi @quietDragon1995, the gene_info_delta_landmark.txt.gz contains an earlier iteration of the landmark gene set (the "deltaprime" set), which was used to compute ~4% of the CMap data. The remaining ~96% was computed using the current version of the landmark gene set (the "epsilon" set). The following links provide more details on how the landmark genes were identified, as well as the difference between the delta and epsilon sets. 

[How were the 1000 landmarks identified?](https://clue.io/connectopedia/identifying_1000_landmarks)
[How is the expression of 1,000 genes measured using Luminex beads?](https://clue.io/connectopedia/measuring_expr_of_1000_genes) -- section titled "A note on versioning of landmark gene sets"
[Guide to LINCS data release in NCBI GEO - L1000](https://clue.io/connectopedia/guide_to_geo_l1000_data)

**Comment by quietDragon1995** [comment]
Thanks for your help!
