### ISSUE TITLE
There should be ~14,000 CRISPR signatures in SigCom LINCS

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/sigcom-lincs#41]

**Comment by jeevangelista** [comment]
Hi Avi, there are 14k signatures
<img width="433" alt="Screen Shot 2021-11-01 at 10 08 55 AM" src="https://user-images.githubusercontent.com/1305807/139684972-c5db5840-a5e1-43a3-bcd6-80e17709fbb5.png">

This image, on the other hand, shows the unique perturbagens i.e. there are 7492 genes that were used for CRISPR knockouts. I'll fix the wording if this is confusing
<img width="452" alt="Screen Shot 2021-11-01 at 10 09 43 AM" src="https://user-images.githubusercontent.com/1305807/139685079-1eff9f54-5ccc-4e97-a81c-31dc1d084e6e.png">
