### ISSUE TITLE
wrong download link for CRISPR KO Consensus Signatures

### ISSUE THREAD

**Issue by ivokwee** [MaayanLab/sigcom-lincs#58]
The link is:

https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/means/cpr_mean_coeff_mat.tsv.gz

Should be:

https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/means/xpr_mean_coeff_mat.tsv.gz

**Comment by jeevangelista** [comment]
Fixed
