### ISSUE TITLE
Unable to download the dataset from SigCom LINCS website 

### ISSUE THREAD

**Issue by dahw0706** [MaayanLab/sigcom-lincs#59]
Hi, 

We would like to download the dataset (ex. [LINCS L1000 CRISPR Perturbations (2021)](https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/gctx/cd-coefficient/xpr_coeff_mat.gctx))from SigCom LINCS, but the download can't be proceeded. While we tried the other download links from [Download](https://maayanlab.cloud/sigcom-lincs/#/Download) page, just found other dataset can't be download either. It would be much appreciated if anyone can help to fix this issue. Thanks!

Best,
TJ

**Comment by u8sand** [comment]
@dahw0706 These downloads are served through AWS's S3 service. If your browser is interrupting the connection you can alternatively use `wget` which supports "continuing" the download:
```bash
wget -c "https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/gctx/cd-coefficient/xpr_coeff_mat.gctx"
```

Alternatively you may have better luck with an s3 client. For example, with [rclone](https://rclone.org/s3/):
```
rclone copy -P ':s3,provider=AWS,anon=True:lincs-dcic/LINCS-sigs-2021/gctx/cd-coefficient/xpr_coeff_mat.gctx' .
```

**Comment by shkao** [comment]
Hi [u8sand](https://github.com/u8sand),

Thanks for the suggestion. However, in my case, I can't reach the host lincs-dcic.s3.amazonaws.com:

```
(base) [shkao@server tmp]$ wget -vc "https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/gctx/cd-coefficient/xpr_coeff_mat.gctx"
--2022-07-25 15:35:09--  https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/gctx/cd-coefficient/xpr_coeff_mat.gctx
Resolving lincs-dcic.s3.amazonaws.com (lincs-dcic.s3.amazonaws.com)... failed: Name or service not known.
wget: unable to resolve host address ‘lincs-dcic.s3.amazonaws.com’
```

**Comment by u8sand** [comment]
@shkao We're sorry to hear that. This seems like some kind of DNS issue or perhaps AWS is blocked on your network? At this time, it is cost prohibitive for us to serve these files outside of S3..

**Comment by dahw0706** [comment]
@u8sand It looks like a DNS issue from our end. The download function works fine now after DNS fixed. Thanks for the help.
