### ISSUE TITLE
Availability of the data matrix for UMAP analysis

### ISSUE THREAD

**Issue by shkao** [MaayanLab/sigcom-lincs#63]
Hi,

I'm looking for certain genes in the interactive plotly UMAP.
For example, I would like to know where TP53 is located in [PC3-specific CRISPR Knockout Signatures](https://maayanlab.cloud/sigcom-lincs/#/UMAPs/xpr-PC3_i).

I'm trying to hover over the whole plot and check the label, which is not very efficient for me. Would it be possible to provide the results of the UMAP, so that we can quickly locate the gene and its neighbors, for example:

```
UMAP-1, UMAP-2, Gene, Cluster
8, 9, INTS4, 13
11, 6, GPRC6A, 8
```

![image](https://user-images.githubusercontent.com/4758311/202342749-1f386a95-4c6a-4243-be70-28cb234d3864.png)

Also, at the top right corner of the UMAP page it says:

```
Signature queries: 4621
Gene queries: 754
```

However, by analyzing [LINCS L1000 CRISPR Perturbations (2021)](https://lincs-dcic.s3.amazonaws.com/LINCS-sigs-2021/gctx/cd-coefficient/xpr_coeff_mat.gctx) downloaded from SigCom, in celline `PC3`, I found 10,641 signatures from 5,096 genes.
What would be the potential reasons for this inconsistency?
(Signature queries: 4,621 vs 10,641; Gene queries: 754 vs 5,096)

**Comment by u8sand** [comment]
With respect to question about the metadata, this is a reasonable request, we will see what we can do about providing this metadata perhaps as an additional download on the portal.

With respect to the counts, these counts " queries" has to do with the user submissions to the web portal and not to do with the actual number of signatures and genes, so these numbers are not expected to match.

**Comment by shkao** [comment]
Hi @u8sand ,

Thanks! Would you know what are the raw values for the UMAP analysis? Log2 fold change or Characteristic Direction values?

**Comment by u8sand** [comment]
@shkao This UMAP was made using the `LINCS L1000 CRISPR Perturbations (2021)` (https://maayanlab.cloud/sigcom-lincs/#/Download) file, which is characteristic direction coefficients.

Attached is this file request, we plan on adding it to the downloads soon.
[xpr_expanded.tsv.gz](https://github.com/MaayanLab/sigcom-lincs/files/10107577/xpr_expanded.tsv.gz)
