### ISSUE TITLE
Transcription Factor Targets?

### ISSUE THREAD

**Issue by dbolser** [MaayanLab/sigcom-lincs#79]
Hi, I went from here:
https://maayanlab.cloud/Harmonizome/search?q=Transcription%20Factor%20Targets&t=dataset

to here:
https://maayanlab.cloud/Harmonizome/dataset/CHEA+Transcription+Factor+Targets

to here:
https://pubmed.ncbi.nlm.nih.gov/20709693/

to here:
http://amp.pharm.mssm.edu/lib/chea.jsp

but found myself here:
https://maayanlab.cloud/sigcom-lincs/#/SignatureSearch/UpDown

Do you provide Transcription Factor Targets, or is the redirect a false positive?

Many thanks,
Dan.

**Comment by AviMaayan** [comment]
Hi @dbolser the redirect for http://amp.pharm.mssm.edu/lib/chea.jsp should go to https://maayanlab.cloud/chea3/. Thank you for letting us know about this issue.

**Comment by dbolser** [comment]
Thanks for the quick reply!

**Comment by u8sand** [comment]
Done

**Comment by dbolser** [comment]
Sorry for the basic question, but is there a simple tf / gene association
file?

**Comment by AviMaayan** [comment]
No. This is because we have ~18M tf/gene associations under "Download" here. If you want to know TF upstream of a specific gene, you can try: https://maayanlab.cloud/Enrichr/#find. If you want to know the targets for a specific TF, you can try: https://maayanlab.cloud/Enrichr/#metadata

**Comment by dbolser** [comment]
Great! Where can I read more about the 18 million?

**Comment by AviMaayan** [comment]
Keenan AB, Torre D, Lachmann A, Leong AK, Wojciechowicz ML, Utti V, Jagodnik KM, Kropiwnicki E, Wang Z, Ma'ayan A. ChEA3: transcription factor enrichment analysis by orthogonal omics integration. Nucleic Acids Res. 2019 Jul 2;47(W1):W212-W224. doi: 10.1093/nar/gkz446. PMID: 31114921; PMCID: PMC6602523.
