### ISSUE TITLE
Missing LINCS L1000 Chemical Perturbagens library on result page

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/sigcom-lincs#80]
On the search results page, I can't find the LINCS L1000 Chemical Perturbagens library. 
@AviMaayan @jeevangelista

**Comment by jeevangelista** [comment]
can you give more info/screenshots?

**Comment by heesukim628** [comment]
From [Playbook use case 3 ](https://playbook-workflow-builder.cloud/report/4153d6c3-0d1f-ba10-eeb6-c7792318c042) there are stage 'Extract LINCS L1000 Chemical Perturbagens - Resolved drugs from the LINCS L1000 Chemical Perturbagens library'. And from the result page of SigCom LINCS, I can't find the perturbagens library card. I checked other perturbations card but couldn't find what has the same result as playbook shows. 

Below are inputs and outputs from playbook. 

<Up Genes>
ABCB5
CA5A
CACNA2D3-AS1
CDKN2A
CHL1-AS1
EDA2R
EYA4
FGF5
FGF6
HNRNPMP1
KCNG4
LINC01479
LMO3
LOC101927023
MTHFD2P1
PTCHD4
PYHIN1
SCGB3A2
SPATA18
TUFMP1
ZMAT3

<Down Genes>
AGTR2
CLP1
FASTKD5
GDF3
GML
HPS6
LINC00911
LOC102724710
MAD2L1BP
OTUD6A
PCAT4
RIT2
SFTPA1
SMG8
STRA8
TEX13C
TUBB2BP1
ZNF518B

<Result>
![image](https://github.com/MaayanLab/sigcom-lincs/assets/118917155/fada0539-0789-41fd-aad9-9afdc12ef731)

**Comment by u8sand** [comment]
It's this one?
![image](https://github.com/MaayanLab/sigcom-lincs/assets/1341861/f5d1d04f-e288-4789-92e9-2a45268ba9f9)

**Comment by heesukim628** [comment]
That library shows a Z score of ZM-241385 as -5.043 but playbook table shows a Z score of 2.56?
![image](https://github.com/MaayanLab/sigcom-lincs/assets/118917155/d20e6d47-227a-4529-981e-9958bddf9a5a)

**Comment by u8sand** [comment]
Okay, it works properly with gene sets
![image](https://github.com/MaayanLab/sigcom-lincs/assets/1341861/70f76960-8cc1-4485-a574-e56c6f9898ce)

But it doesn't seem to work properly with up/down sets
![image](https://github.com/MaayanLab/sigcom-lincs/assets/1341861/55ba33e2-d98b-4273-a614-7f7402b24c88)

**Comment by u8sand** [comment]
Confirmed this is an issue with the playbook and not sigcom-lincs

Basically it has to do with how we're turning two z scores (z-up/z-down) into one. will fix the calculation to be more intuitive

**Comment by u8sand** [comment]
These are now aligned by using sigcom-lincs data API's `z-sum` field.
We'll want to discuss which method we want to use to compute `z-sum`
